In [1]:
import os
import pandas as pd
import numpy as np
from scipy.optimize import curve_fit
import matplotlib.pyplot as plt

df = pd.read_csv('nutA1.csv', delimiter=';')
df

,Volume Tandon (L),Waktu (s),TDS Awal (ppm),TDS Akhir (ppm),Delta TDS (ppm),Rata Rata Delta TDS (ppm)
0,40,0,257,261,4,"4,4"
1,40,0,261,266,5,NaN
2,40,1,266,270,4,NaN
3,40,1,270,275,5,NaN
4,40,1,275,279,4,NaN
...,...,...,...,...,...,...
4195,100,60,430,569,139,NaN
4196,100,60,569,705,136,NaN
4197,100,60,705,838,133,NaN
4198,100,60,838,980,142,NaN
4199,100,60,980,1113,133,NaN

In [2]:
dataset = df[["Volume Tandon (L)", "Waktu (s)", "Delta TDS (ppm)"]]
dataset

      Volume Tandon (L)  Waktu (s)  Delta TDS (ppm)
0                    40          0                4
1                    40          0                5
2                    40          1                4
3                    40          1                5
4                    40          1                4
...                 ...        ...              ...
4195                100         60              139
4196                100         60              136
4197                100         60              133
4198                100         60              142
4199                100         60              133

[4200 rows x 3 columns]

# Volume 40

In [16]:
import pandas as pd

# Membuat DataFrame dari data
df = dataset[dataset["Volume Tandon (L)"]==40]

# Menentukan alpha untuk smoothing eksponensial
alpha = 0.3

# Mengaplikasikan smoothing eksponensial pada DeltapH
df['DeltapH_Smooth'] = df["Delta TDS (ppm)"].ewm(alpha=alpha, adjust=False).mean()

print("Data setelah menerapkan smoothing eksponensial:")
df
average_df = df.groupby(["Volume Tandon (L)", "Waktu (s)"]).mean()[["DeltapH_Smooth"]]
df_40 = average_df.reset_index()
df_40

Data setelah menerapkan smoothing eksponensial:

C:\Users\IDEAPA~1\AppData\Local\Temp/ipykernel_8684/2107926446.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['DeltapH_Smooth'] = df["Delta TDS (ppm)"].ewm(alpha=alpha, adjust=False).mean()

    Volume Tandon (L)  Waktu (s)  DeltapH_Smooth
0                  40          0        4.150000
1                  40          1        4.655878
2                  40          2        8.737345
3                  40          3       12.173727
4                  40          4       13.735036
..                ...        ...             ...
56                 40         56      245.628656
57                 40         57      250.289989
58                 40         58      255.724734
59                 40         59      259.837239
60                 40         60      262.907427

[61 rows x 3 columns]

# Volume 50

In [17]:
import pandas as pd

# Membuat DataFrame dari data
df = dataset[dataset["Volume Tandon (L)"]==50]

# Menentukan alpha untuk smoothing eksponensial
alpha = 0.3

# Mengaplikasikan smoothing eksponensial pada DeltapH
df['DeltapH_Smooth'] = df["Delta TDS (ppm)"].ewm(alpha=alpha, adjust=False).mean()

print("Data setelah menerapkan smoothing eksponensial:")
df
average_df = df.groupby(["Volume Tandon (L)", "Waktu (s)"]).mean()[["DeltapH_Smooth"]]
df_50 = average_df.reset_index()
df_50

Data setelah menerapkan smoothing eksponensial:

C:\Users\IDEAPA~1\AppData\Local\Temp/ipykernel_8684/2045850500.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['DeltapH_Smooth'] = df["Delta TDS (ppm)"].ewm(alpha=alpha, adjust=False).mean()

    Volume Tandon (L)  Waktu (s)  DeltapH_Smooth
0                  50          1        4.386752
1                  50          2        7.759127
2                  50          3       12.143599
3                  50          4       15.902610
4                  50          5       17.741480
5                  50          6       21.648718
6                  50          7       27.691802
7                  50          8       33.167158
8                  50          9       36.814132
9                  50         10       40.111024
10                 50         11       44.077001
11                 50         12       48.208294
12                 50         13       52.636248
13                 50         14       56.203123
14                 50         15       58.631343
15                 50         16       64.503598
16                 50         17       66.542801
17                 50         18       70.595279
18                 50         19       73.823705
19                 50         20       78.272745
20                 50         21       82.041555
21                 50         22       84.928911
22                 50         23       90.860646
23                 50         24       94.137868
24                 50         25       95.014258
25                 50         26      102.268368
26                 50         27      105.346456
27                 50         28      107.488436
28                 50         29      109.806442
29                 50         30      116.399476
30                 50         31      119.358478
31                 50         32      123.944370
32                 50         33      129.701239
33                 50         34      136.375648
34                 50         35      141.277676
35                 50         36      144.743516
36                 50         37      149.407335
37                 50         38      153.944884
38                 50         39      157.878290
39                 50         40      162.569778
40                 50         41      164.761460
41                 50         42      169.863597
42                 50         43      174.552847
43                 50         44      179.423580
44                 50         45      181.763806
45                 50         46      185.791557
46                 50         47      191.012085
47                 50         48      195.432070
48                 50         49      200.617970
49                 50         50      204.818949
50                 50         51      209.846654
51                 50         52      213.762585
52                 50         53      218.107164
53                 50         54      222.655239
54                 50         55      227.756854
55                 50         56      232.622835
56                 50         57      236.824583
57                 50         58      240.996640
58                 50         59      245.757352
59                 50         60      251.249980

# Volume 60

In [18]:
import pandas as pd

# Membuat DataFrame dari data
df = dataset[dataset["Volume Tandon (L)"]==60]

# Menentukan alpha untuk smoothing eksponensial
alpha = 0.3

# Mengaplikasikan smoothing eksponensial pada DeltapH
df['DeltapH_Smooth'] = df["Delta TDS (ppm)"].ewm(alpha=alpha, adjust=False).mean()

print("Data setelah menerapkan smoothing eksponensial:")
df
average_df = df.groupby(["Volume Tandon (L)", "Waktu (s)"]).mean()[["DeltapH_Smooth"]]
df_60 = average_df.reset_index()
df_60

Data setelah menerapkan smoothing eksponensial:

C:\Users\IDEAPA~1\AppData\Local\Temp/ipykernel_8684/4075528024.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['DeltapH_Smooth'] = df["Delta TDS (ppm)"].ewm(alpha=alpha, adjust=False).mean()

    Volume Tandon (L)  Waktu (s)  DeltapH_Smooth
0                  60          1        6.196202
1                  60          2        5.967847
2                  60          3        9.020592
3                  60          4       12.539097
4                  60          5       15.747638
5                  60          6       20.554601
6                  60          7       23.412805
7                  60          8       26.866146
8                  60          9       29.658514
9                  60         10       32.549161
10                 60         11       34.696723
11                 60         12       38.036365
12                 60         13       40.804326
13                 60         14       43.708160
14                 60         15       46.099992
15                 60         16       50.815974
16                 60         17       55.031638
17                 60         18       58.993150
18                 60         19       63.863201
19                 60         20       71.268888
20                 60         21       77.414713
21                 60         22       76.142832
22                 60         23       84.916525
23                 60         24       92.493153
24                 60         25       98.091420
25                 60         26      103.595358
26                 60         27      110.704057
27                 60         28      115.521254
28                 60         29      122.012350
29                 60         30      126.992535
30                 60         31      132.603955
31                 60         32      137.145537
32                 60         33      142.139503
33                 60         34      147.576982
34                 60         35      152.960640
35                 60         36      158.279721
36                 60         37      163.379948
37                 60         38      168.508655
38                 60         39      173.583642
39                 60         40      178.907798
40                 60         41      185.014149
41                 60         42      190.854707
42                 60         43      195.913783
43                 60         44      202.001750
44                 60         45      207.527531
45                 60         46      213.082882
46                 60         47      219.769505
47                 60         48      224.020409
48                 60         49      228.956466
49                 60         50      235.101714
50                 60         51      240.766499
51                 60         52      246.506558
52                 60         53      250.287189
53                 60         54      255.538351
54                 60         55      262.168727
55                 60         56      269.064417
56                 60         57      274.133126
57                 60         58      278.856800
58                 60         59      282.267673
59                 60         60      287.090134

# Volume 70

In [19]:
import pandas as pd

# Membuat DataFrame dari data
df = dataset[dataset["Volume Tandon (L)"]==70]

# Menentukan alpha untuk smoothing eksponensial
alpha = 0.3

# Mengaplikasikan smoothing eksponensial pada DeltapH
df['DeltapH_Smooth'] = df["Delta TDS (ppm)"].ewm(alpha=alpha, adjust=False).mean()

print("Data setelah menerapkan smoothing eksponensial:")
df
average_df = df.groupby(["Volume Tandon (L)", "Waktu (s)"]).mean()[["DeltapH_Smooth"]]
df_70 = average_df.reset_index()
df_70

Data setelah menerapkan smoothing eksponensial:

C:\Users\IDEAPA~1\AppData\Local\Temp/ipykernel_8684/3820811934.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['DeltapH_Smooth'] = df["Delta TDS (ppm)"].ewm(alpha=alpha, adjust=False).mean()

    Volume Tandon (L)  Waktu (s)  DeltapH_Smooth
0                  70          1        4.136906
1                  70          2        5.128986
2                  70          3        7.874102
3                  70          4       10.523380
4                  70          5       13.257497
5                  70          6       15.719172
6                  70          7       18.781287
7                  70          8       21.338909
8                  70          9       23.996611
9                  70         10       26.585300
10                 70         11       28.603434
11                 70         12       31.387408
12                 70         13       33.252923
13                 70         14       36.686069
14                 70         15       38.939617
15                 70         16       43.173790
16                 70         17       48.245044
17                 70         18       51.084980
18                 70         19       55.657641
19                 70         20       60.165874
20                 70         21       63.136476
21                 70         22       66.533701
22                 70         23       68.003614
23                 70         24       71.463910
24                 70         25       75.821514
25                 70         26       79.130004
26                 70         27       81.995601
27                 70         28       84.276017
28                 70         29       87.791132
29                 70         30       91.454516
30                 70         31       95.070081
31                 70         32       99.410201
32                 70         33      102.475325
33                 70         34      106.860737
34                 70         35      110.643660
35                 70         36      113.751763
36                 70         37      116.969044
37                 70         38      119.271633
38                 70         39      123.188361
39                 70         40      126.493872
40                 70         41      130.087610
41                 70         42      133.420604
42                 70         43      137.720059
43                 70         44      140.601465
44                 70         45      143.624055
45                 70         46      148.529473
46                 70         47      152.755343
47                 70         48      155.796193
48                 70         49      158.808230
49                 70         50      161.981474
50                 70         51      165.297138
51                 70         52      168.236372
52                 70         53      170.593453
53                 70         54      173.202410
54                 70         55      175.062218
55                 70         56      179.305418
56                 70         57      183.463037
57                 70         58      186.239928
58                 70         59      190.553321
59                 70         60      192.958644

# Volume 80

In [20]:
import pandas as pd

# Membuat DataFrame dari data
df = dataset[dataset["Volume Tandon (L)"]==80]

# Menentukan alpha untuk smoothing eksponensial
alpha = 0.3

# Mengaplikasikan smoothing eksponensial pada DeltapH
df['DeltapH_Smooth'] = df["Delta TDS (ppm)"].ewm(alpha=alpha, adjust=False).mean()

print("Data setelah menerapkan smoothing eksponensial:")
df
average_df = df.groupby(["Volume Tandon (L)", "Waktu (s)"]).mean()[["DeltapH_Smooth"]]
df_80 = average_df.reset_index()
df_80

Data setelah menerapkan smoothing eksponensial:

C:\Users\IDEAPA~1\AppData\Local\Temp/ipykernel_8684/3880650464.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['DeltapH_Smooth'] = df["Delta TDS (ppm)"].ewm(alpha=alpha, adjust=False).mean()

    Volume Tandon (L)  Waktu (s)  DeltapH_Smooth
0                  80          1        3.147763
1                  80          2        5.169456
2                  80          3        7.829615
3                  80          4       10.653014
4                  80          5       13.057310
5                  80          6       16.219985
6                  80          7       18.375229
7                  80          8       20.945121
8                  80          9       23.208122
9                  80         10       26.529267
10                 80         11       28.615666
11                 80         12       30.611676
12                 80         13       35.176428
13                 80         14       37.089827
14                 80         15       38.487733
15                 80         16       41.618249
16                 80         17       44.707563
17                 80         18       46.231690
18                 80         19       48.034796
19                 80         20       50.766689
20                 80         21       52.648767
21                 80         22       55.179756
22                 80         23       57.201806
23                 80         24       59.642605
24                 80         25       62.349919
25                 80         26       66.099600
26                 80         27       69.039157
27                 80         28       72.053715
28                 80         29       75.212215
29                 80         30       79.377198
30                 80         31       82.176353
31                 80         32       84.458693
32                 80         33       86.546062
33                 80         34       88.587937
34                 80         35       90.933962
35                 80         36       94.041407
36                 80         37       97.356651
37                 80         38      100.493176
38                 80         39      102.527008
39                 80         40      105.989567
40                 80         41      109.141219
41                 80         42      112.973971
42                 80         43      114.173244
43                 80         44      116.526513
44                 80         45      120.003430
45                 80         46      121.191735
46                 80         47      123.699545
47                 80         48      125.519916
48                 80         49      127.730743
49                 80         50      130.951086
50                 80         51      133.338995
51                 80         52      136.800087
52                 80         53      141.384435
53                 80         54      145.945024
54                 80         55      148.725272
55                 80         56      152.086265
56                 80         57      154.828115
57                 80         58      156.985847
58                 80         59      159.630523
59                 80         60      160.577434

# Volume 90

In [21]:
import pandas as pd

# Membuat DataFrame dari data
df = dataset[dataset["Volume Tandon (L)"]==90]

# Menentukan alpha untuk smoothing eksponensial
alpha = 0.3

# Mengaplikasikan smoothing eksponensial pada DeltapH
df['DeltapH_Smooth'] = df["Delta TDS (ppm)"].ewm(alpha=alpha, adjust=False).mean()

print("Data setelah menerapkan smoothing eksponensial:")
df
average_df = df.groupby(["Volume Tandon (L)", "Waktu (s)"]).mean()[["DeltapH_Smooth"]]
df_90 = average_df.reset_index()
df_90

Data setelah menerapkan smoothing eksponensial:

C:\Users\IDEAPA~1\AppData\Local\Temp/ipykernel_8684/1372627765.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['DeltapH_Smooth'] = df["Delta TDS (ppm)"].ewm(alpha=alpha, adjust=False).mean()

    Volume Tandon (L)  Waktu (s)  DeltapH_Smooth
0                  90          1        1.880753
1                  90          2        4.791032
2                  90          3        7.159280
3                  90          4        9.328420
4                  90          5       11.783425
5                  90          6       14.344922
6                  90          7       17.050244
7                  90          8       19.558130
8                  90          9       20.666270
9                  90         10       23.939410
10                 90         11       24.956632
11                 90         12       27.659453
12                 90         13       30.609171
13                 90         14       31.507860
14                 90         15       33.681248
15                 90         16       35.978761
16                 90         17       38.924206
17                 90         18       41.544362
18                 90         19       43.695296
19                 90         20       45.738979
20                 90         21       47.321521
21                 90         22       49.614343
22                 90         23       51.334770
23                 90         24       53.904184
24                 90         25       55.611487
25                 90         26       58.554235
26                 90         27       60.432597
27                 90         28       63.026049
28                 90         29       65.367080
29                 90         30       67.636084
30                 90         31       69.228146
31                 90         32       70.292327
32                 90         33       69.976529
33                 90         34       70.826879
34                 90         35       73.672839
35                 90         36       77.232363
36                 90         37       79.346879
37                 90         38       81.411221
38                 90         39       82.941944
39                 90         40       85.050128
40                 90         41       87.163666
41                 90         42       88.691870
42                 90         43       91.507745
43                 90         44       92.574462
44                 90         45       95.039191
45                 90         46       96.610252
46                 90         47       99.280851
47                 90         48      100.374461
48                 90         49      103.044852
49                 90         50      105.387035
50                 90         51      107.589745
51                 90         52      108.916089
52                 90         53      110.312961
53                 90         54      112.949758
54                 90         55      114.595715
55                 90         56      116.084872
56                 90         57      117.573088
57                 90         58      119.854602
58                 90         59      120.986117
59                 90         60      125.557872

# Volume 100

In [22]:
import pandas as pd

# Membuat DataFrame dari data
df = dataset[dataset["Volume Tandon (L)"]==100]

# Menentukan alpha untuk smoothing eksponensial
alpha = 0.3

# Mengaplikasikan smoothing eksponensial pada DeltapH
df['DeltapH_Smooth'] = df["Delta TDS (ppm)"].ewm(alpha=alpha, adjust=False).mean()

print("Data setelah menerapkan smoothing eksponensial:")
df
average_df = df.groupby(["Volume Tandon (L)", "Waktu (s)"]).mean()[["DeltapH_Smooth"]]
df_100 = average_df.reset_index()
df_100

Data setelah menerapkan smoothing eksponensial:

C:\Users\IDEAPA~1\AppData\Local\Temp/ipykernel_8684/3377802290.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['DeltapH_Smooth'] = df["Delta TDS (ppm)"].ewm(alpha=alpha, adjust=False).mean()

    Volume Tandon (L)  Waktu (s)  DeltapH_Smooth
0                 100          1        1.954253
1                 100          2        4.158031
2                 100          3        5.661456
3                 100          4        8.756897
4                 100          5       11.076911
5                 100          6       12.946363
6                 100          7       15.120591
7                 100          8       17.486868
8                 100          9       20.027157
9                 100         10       21.919075
10                100         11       23.861926
11                100         12       26.056967
12                100         13       29.072873
13                100         14       31.384310
14                100         15       34.592269
15                100         16       35.735969
16                100         17       37.693565
17                100         18       40.149993
18                100         19       42.033326
19                100         20       45.596809
20                100         21       47.809671
21                100         22       50.255698
22                100         23       52.486277
23                100         24       54.467302
24                100         25       57.072529
25                100         26       59.188713
26                100         27       61.742507
27                100         28       64.457072
28                100         29       66.721657
29                100         30       69.253885
30                100         31       71.593786
31                100         32       74.400771
32                100         33       79.265230
33                100         34       81.875793
34                100         35       83.655337
35                100         36       86.235410
36                100         37       86.890196
37                100         38       89.205761
38                100         39       92.233076
39                100         40       96.142519
40                100         41       97.270003
41                100         42      101.353257
42                100         43      103.019818
43                100         44      104.223207
44                100         45      106.062023
45                100         46      108.035370
46                100         47      108.726589
47                100         48      111.468891
48                100         49      113.995962
49                100         50      116.199698
50                100         51      117.698252
51                100         52      119.759727
52                100         53      122.132551
53                100         54      124.798358
54                100         55      125.843145
55                100         56      127.198415
56                100         57      130.111451
57                100         58      132.330896
58                100         59      135.175556
59                100         60      137.511380

In [23]:
df_combined = pd.concat([df_40, df_50, df_60, df_70, df_80, df_90, df_100], axis=0)
df_nutAE = df_combined.reset_index()
df_nutAE

     index  Volume Tandon (L)  Waktu (s)  DeltapH_Smooth
0        0                 40          0        4.150000
1        1                 40          1        4.655878
2        2                 40          2        8.737345
3        3                 40          3       12.173727
4        4                 40          4       13.735036
..     ...                ...        ...             ...
416     55                100         56      127.198415
417     56                100         57      130.111451
418     57                100         58      132.330896
419     58                100         59      135.175556
420     59                100         60      137.511380

[421 rows x 4 columns]

In [24]:
# Menyimpan DataFrame menjadi file CSV
df_nutAE.to_csv('nuta_Eksponensial.csv', index=False)

print("DataFrame berhasil diekspor menjadi file CSV!")

DataFrame berhasil diekspor menjadi file CSV!